config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'view_deck' => 'decks#show'
  get 'create_deck' => 'decks#new'
  post 'create_deck' => 'decks#create'
  resources :users
  resources :decks

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  validates(:name, { presence: true, length: { maximum: 50 } })
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :decks
  attr_accessor :remember_token

  before_save { self.email = email.downcase }

  validates(:name, { presence: true, length: { maximum: 50 } })

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates(:email, { presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false } })

  has_secure_password

  validates(:password, { presence: true, length: { minimum: 6 }, allow_nil: true })

  # returns the hash digest of the given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # returns a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # saves a remember token to the database as remember_digest
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # returns true if the given token matches the digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # forgets the current user
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def show
  end

  def new
    @deck = Deck.new
  end

  def create
    @user = current_user
    deck = params[:deck][:deck].split(',')
    @deck = Deck.new(name: params[:deck][:name], deck: deck, user_id: @user[:id])
    @deck.save
    redirect_to @user
  end

  def edit
    @deck = Deck.find(params[:id])
  end

  def update
    @user = current_user
    @deck = Deck.find_by(id: params[:id])
    new_deck = params[:deck][:deck].split(',')
    if @deck.update_attributes(deck: new_deck)
      flash[:success] = "Deck Saved Successfully"
      redirect_to @user
    else
      render "edit"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

#######  RESTful architecture #######

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @decks = Deck.where(user_id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # successful registration
      log_in(@user)
      flash[:success] = "Welcome to Decksmith!"
      redirect_to @user
    else
      # unsuccessful registration
      render "new"
    end
  end

  def edit
    # @user = User.find(params[:id]) is no longer needed due to the current_user
    # method and before_action call.
  end

  def update
    # @user = User.find(params[:id]) no longer needed, see 'edit'
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Before filters

    # confirms a logged in user
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end

    # confirms the correct user
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # returns the full title per page
  def full_title(page_title = '')
    base_title = "Decksmith"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  # remembers a user in a persistent session
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # returns true if the given user is the current user
  def current_user?(user)
    user == current_user
  end

  # returns the current user
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      @user = User.find_by(id: user_id)
      if @user && @user.authenticated?(cookies[:remember_token])
        log_in(@user)
        @current_user = @user
      end
    end
  end

  # returns true if the use is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end

  # forgets a persistent session
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # logs out the current user
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # redirects to stored location (of to the default)
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # stores the url trying to be accessed
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # returns the gravatar for the given user
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/decks/edit.html.erb
<% provide(:title, "Edit Deck") %>
<div class="row">
  <div class="col-xs-12 col-md-4 col-md-offset-4">
    <h1>Edit <%= @deck[:name] %></h1>
  </div>
  <div class="col-xs-12 col-md-2">
    <button type="button" class="btn btn-primary col-md-6" data-toggle="modal" data-target="#save" id="saveDeck">Save</button>
  </div>
</div>

<div class="row">
  <div class="col-md-12 ui-droppable" id="cardDropZone">
  </div>
</div>
<h2 id="expandView"><em>expand view</em> <span class="glyphicon glyphicon-zoom-in"></span></h2>

<!-- holder for the carousel -->
<div id="carousel-me">

</div>

<!-- Save modal -->
<div class="modal fade" id="save" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Save Deck</h4>
      </div>
      <div class="modal-body col-md-10 col-md-offset-1">
        <%= form_for(@deck) do |f| %>
          <%= f.hidden_field :deck, id: "deckArray" %>

          <%= f.text_field :name, class: "form-control", placeholder: "Name your deck" %>
      </div>
      <div class="modal-footer">
          <%= f.button "Cancel", class: "btn btn-default", "data-dismiss" => "modal", "type" => "button" %>
          <%= f.submit "Save Deck", class: "btn btn-primary col-md-4" %>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">

  function getCards() {
    var cardArray = <%= @deck[:deck].to_json.html_safe %>;
    for (var i = 0; i < cardArray.length; i++) {
      var xhr = new XMLHttpRequest();
      xhr.open('get', 'https://api.deckbrew.com/mtg/cards/' + cardArray[i], false);
      xhr.onload = function() {
        if (xhr.readyState != XMLHttpRequest.DONE) {
          return;
        }
        if (xhr.status == 200) {
          var response = JSON.parse(xhr.responseText);
          var div = document.createElement('div');
          div.classList.add('mini');
          div.id = response["id"];
          div.style.width = "112px";
          div.style.height = "156px";
          div.style.backgroundImage = "url('" + response["editions"][0]["image_url"] + "')";
          var close = document.createElement('span');
          close.classList.add("glyphicon");
          close.classList.add("glyphicon-remove");
          close.style.float = "right";
          div.appendChild(close);
          close.addEventListener("click", function() {
            $(this.parentElement).remove();
          });
          document.getElementById('cardDropZone').appendChild(div);
        }
      };
      xhr.send(null);
    }
  }

  ///////////////////////////////////////////////////////////////////////
  ///////////////////    Carousel functions    //////////////////////////
  ///////////////////////////////////////////////////////////////////////

  var getSet = function(page) {
    // console.log("getSet has been called");
    var response;

    var getResponse = function(data) {
      // console.log("getResponse has been called");
      response = data;
    }
    var xhr = new XMLHttpRequest();
    xhr.open("get", "https://api.deckbrew.com/mtg/cards?set=BFZ&page=" + page, false);
    xhr.onreadystatechange = function() {
      if (xhr.readyState != XMLHttpRequest.DONE) {
        return;
      }
      // console.log(xhr.status);
      if (xhr.status == 200) {
        var data = JSON.parse(xhr.responseText);
        getResponse(data);
      }
    };
    xhr.send(null);

    return response;
  };

  var createItems = function(pages) {
    // console.log("createItems has been called");
    var cardCarousel = document.createElement('div');
    cardCarousel.id = "card-carousel";
    cardCarousel.classList.add("carousel");
    cardCarousel.classList.add("slide");
    cardCarousel.setAttribute("data-ride", "carousel");
    var carouselWrapper = document.createElement('div');
    carouselWrapper.id = "carousel-wrapper";
    carouselWrapper.classList.add("carousel-inner");
    carouselWrapper.setAttribute("role", "listbox");

    var count = 0;
    for (var i = 0; i < pages; i++) {
      var pageCount = 0;
      var response = getSet(i);
      // console.log(response);

      for (var j = 0; j < response.length; j+=5) {
        var item = document.createElement('div');
        item.classList.add("item");
        if (count == 0) {
          item.classList.add("active");
        }
        var inc = 0;
        while (inc < 5 && pageCount < response.length) {
          var img = document.createElement('img');
          // console.log(count);
          var url = response[(pageCount).toString()]["editions"][0]["image_url"];
          img.src = url;
          img.alt = response[(pageCount).toString()]["name"];
          img.setAttribute("id", response[(pageCount).toString()]["id"]);
          img.style.display = "inline";
          img.classList.add("card");
          img.style.zIndex = 999;
          img.setAttribute("data-toggle", "modal");
          img.setAttribute("data-target", "#cardModal");
          item.appendChild(img);
          inc++;
          count++;
          pageCount++;
        }
        carouselWrapper.appendChild(item);
      }
    }
    cardCarousel.appendChild(carouselWrapper);

    var a1 = document.createElement('a');
    a1.classList.add("left");
    a1.classList.add("carousel-control");
    a1.href = "#card-carousel";
    a1.setAttribute("role", "button");
    a1.setAttribute("data-slide", "prev");
    var leftIcon = document.createElement('span');
    leftIcon.classList.add("glyphicon");
    leftIcon.classList.add("glyphicon-chevron-left");
    leftIcon.setAttribute("aria-hidden", "true");
    a1.appendChild(leftIcon);
    var sr = document.createElement('span');
    sr.classList.add("sr-only");
    sr.innerText = "Previous";
    a1.appendChild(sr);

    var a2 = document.createElement('a');
    a2.classList.add("right");
    a2.classList.add("carousel-control");
    a2.href = "#card-carousel";
    a2.setAttribute("role", "button");
    a2.setAttribute("data-slide", "next");
    var rightIcon = document.createElement('span');
    rightIcon.classList.add("glyphicon");
    rightIcon.classList.add("glyphicon-chevron-right");
    rightIcon.setAttribute("aria-hidden", "true");
    a2.appendChild(rightIcon);
    var sr2 = document.createElement('span');
    sr2.classList.add("sr-only");
    sr2.innerText = "Next";
    a2.appendChild(sr2);

    cardCarousel.appendChild(a1);
    cardCarousel.appendChild(a2);
    document.getElementById('carousel-me').appendChild(cardCarousel);
  };

  ///////////////////////////////////////////////////////////////////////
  ///////////////////   Expand and Collapse    //////////////////////////
  ///////////////////////////////////////////////////////////////////////

  function expandIt() {
    var view = document.getElementById('cardDropZone');
    view.style.height = "100%";
    expand.innerHTML = "collapse <span class='glyphicon glyphicon-zoom-out'></span>";
    expanded = true;
  }

  function collapseIt() {
    var view = document.getElementById('cardDropZone');
    view.style.height = "340px";
    expand.innerHTML = "expand view <span class='glyphicon glyphicon-zoom-in'></span>";
    document.getElementById('cardDropZone').scrollTop = 0;
    window.scroll(0,0);
    expanded = false;
  }

  var expand = document.getElementById('expandView');
  var expanded = false;
  expand.addEventListener("click", function() {
    if (expanded) {
      collapseIt();
    } else {
      expandIt();
    }
  });

  ///////////////////////////////////////////////////////////////////////
  ///////////////////       Deck Saving        //////////////////////////
  ///////////////////////////////////////////////////////////////////////

  document.getElementById('saveDeck').addEventListener("click", getDeck);

  function getDeck() {
    console.log("getDeck called");
    var deckArray = [];
    var dropZone = document.getElementById('cardDropZone');
    var deckCards = dropZone.children;
    for (var i = 0; i < deckCards.length; i++) {
      deckArray.push(deckCards[i]["id"]);
    }
    console.log(deckArray);
    document.getElementById('deckArray').value = deckArray;
  }

  $(document).ready(function() {
    getCards();
    createItems(3);

    $(".card").draggable({
      cursor: "move",
      grid: [10, 10],
      helper: "clone",
      containment: "window",
      zIndex: 100
    });

    $("#cardDropZone").droppable({
      accept: ".card",
      drop: function(event, ui) {
        var droppedItem = $(ui.draggable).clone();
        var div = document.createElement('div');
        // console.log(div);
        // console.log(droppedItem[0].src);
        $(div).css("background-image", "url('" + droppedItem[0].src + "')");
        $(div).css("width", "112px");
        $(div).css("height", "156px");
        div.classList.add("mini");
        div.id = droppedItem[0].id;
        var close = document.createElement('span');
        close.classList.add("glyphicon");
        close.classList.add("glyphicon-remove");
        close.style.float = "right";
        div.appendChild(close);
        close.addEventListener("click", function() {
          $(div).remove();
        });
        var drags = document.getElementById('dragHere');
        if (drags) {
          drags.remove();
        }
        $(this).append(div);
      }
    });


  });
</script>

app/views/decks/show.html.erb
<h1>Show</h1>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <small>Jeff Steed &copy; 2016</small>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
    <!-- <%= debug(params) if Rails.env.development? %> -->
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapseNav" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Decksmith", root_url, id: "logo" %>
    </div>

    <nav class="collapse navbar-collapse" id="collapseNav">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_url %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container" id="bodyContainer">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
  </div>
  <div class="container">
    <%= render "layouts/footer" %>
  </div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Email me at <a href="http://mail.google.com" target="_blank">steed.jeff@gmail.com</a>
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to Decksmith!</h1>
  <h2>A Magic: The Gathering&copy; deck building app</h2>
  <%= link_to "Sign up now!", signup_path , class: "btn btn-lg btn-primary" %>
</div>
<!--<%= link_to image_tag('logo.png', alt: "Logo", class: "logo"), "#" %>-->

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render "shared/error_messages" %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Save changes", class: "btn btn-primary"%>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for(user, size: 50) %>
      <%= link_to(user.name, user) %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render "shared/error_messages" %>

        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>

        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>

        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>

        <%= f.submit "Create my account!", class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-2 col-md-offset-1">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-5" id="deckOptions">
    <div class="col-md-12" id="deckList">

      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">
              Saved Decks
            </th>
            <th scope="col">
              # of cards
            </th>
          </tr>
        </thead>
        <tbody>
          <% if @decks != nil %>
            <% @decks.each do |deck| %>
              <tr>
                <td>
                  <a href="<%= edit_deck_path(deck[:id]) %>"><%= deck[:name] %></a>
                </td>
                <td id="nums">
                  <%= deck[:deck].length %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-md-3" id="create">
    <div class="col-md-12">
      <a href="<%= create_deck_path %>">
        <div id="createDeck">
          <h1>Deck Builder</h1>
          <!-- <%= link_to "Deck Builder", create_deck_path %> -->
        </div>
      </a>
    </div>
  </div>
</div>

<!-- <script type="text/javascript">
  window.tdiff = []; fred = function(a,b){return a-b;};
  window.document.onload = function(e){
    console.log("document.onload", e, Date.now() ,window.tdiff,
    (window.tdiff[0] = Date.now()) && window.tdiff.reduce(fred) );
  }
  window.onload = function(e){
    console.log("window.onload", e, Date.now() ,window.tdiff,
    (window.tdiff[1] = Date.now()) && window.tdiff.reduce(fred) );
  }
  $(document).ready(function(e) {
    console.log("$(document).ready()", e, Date.now() ,window.tdiff,
    (window.tdiff[1] = Date.now()) && window.tdiff.reduce(fred) );
  });
</script> -->

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>